return {
    {x = 1, y = 1, width = 16, height = 16, name = "bottom_left", type = "wall", style = "winter_forest", bitvalue = 6},
    {x = 19, y = 1, width = 16, height = 16, name = "bottom_centre", type = "wall", style = "winter_forest", bitvalue = 14},
    {x = 37, y = 1, width = 16, height = 16, name = "bottom_right", type = "wall", style = "winter_forest", bitvalue = 12},
    {x = 1, y = 19, width = 16, height = 16, name = "centre_left", type = "wall", style = "winter_forest", bitvalue = 7},
    {x = 19, y = 19, width = 16, height = 16, name = "centre_centre", type = "wall", style = "winter_forest", bitvalue = 15},
    {x = 37, y = 19, width = 16, height = 16, name = "centre_right", type = "wall", style = "winter_forest", bitvalue = 13},
    {x = 1, y = 37, width = 16, height = 16, name = "top_left", type = "wall", style = "winter_forest", bitvalue = 3},
    {x = 19, y = 37, width = 16, height = 16, name = "top_centre", type = "wall", style = "winter_forest", bitvalue = 11},
    {x = 37, y = 37, width = 16, height = 16, name = "top_right", type = "wall", style = "winter_forest", bitvalue = 9},
    {x = 55, y = 1, width = 16, height = 16, name = "jut_down", type = "wall", style = "winter_forest", bitvalue = 1},
    {x = 55, y = 19, width = 16, height = 16, name = "jut_up", type = "wall", style = "winter_forest", bitvalue = 4},
    {x = 55, y = 37, width = 16, height = 16, name = "jut_right", type = "wall", style = "winter_forest", bitvalue = 8},
    {x = 55, y = 55, width = 16, height = 16, name = "jut_left", type = "wall", style = "winter_forest", bitvalue = 2},
    {x = 1, y = 55, width = 16, height = 16, name = "horizontal", type = "wall", style = "winter_forest", bitvalue = 10},
    {x = 19, y = 55, width = 16, height = 16, name = "vertical", type = "wall", style = "winter_forest", bitvalue = 5},
    {x = 73, y = 1, width = 16, height = 16, name = "floor_a", type = "floor", style = "winter_forest", bitvalue = 0},
    {x = 73, y = 19, width = 16, height = 16, name = "floor_b", type = "floor", style = "winter_forest", bitvalue = 0},
    {x = 73, y = 37, width = 16, height = 16, name = "floor_c", type = "floor", style = "winter_forest", bitvalue = 0},
    {x = 92, y = 1, width = 12, height = 18, name = "tree_a", type = "tree", style = "winter_forest", bitvalue = 1000, yoffset=4, xoffset=0},
    {x = 106, y = 1, width = 16, height = 26, name = "tree_b", type = "tree", style = "winter_forest", bitvalue = 1001, yoffset=10, xoffset=0},
    {x = 124, y = 1, width = 12, height = 26, name = "tree_c", type = "tree", style = "winter_forest", bitvalue = 1002, yoffset=10, xoffset=0},
    {x = 137, y = 1, width = 26, height = 30, name = "tree_d", type = "tree", style = "winter_forest", bitvalue = 1003, yoffset=14, xoffset=5},
    {x = 92, y = 33, width = 12, height = 18, name = "tree_a", type = "tree", style = "winter_forest", bitvalue = 1004, yoffset=4, xoffset=0},
    {x = 106, y = 33, width = 16, height = 26, name = "tree_b", type = "tree", style = "winter_forest", bitvalue = 1005, yoffset=10, xoffset=0},
    {x = 124, y = 33, width = 12, height = 26, name = "tree_c", type = "tree", style = "winter_forest", bitvalue = 1006, yoffset=10, xoffset=0},
    {x = 137, y = 33, width = 26, height = 30, name = "tree_d", type = "tree", style = "winter_forest", bitvalue = 1007, yoffset=14, xoffset=5},
    {x = 99, y = 65, width = 31, height = 42, name = "drop_tree_a", type = "tree", style = "winter_forest", bitvalue = 8000, yoffset=21, xoffset=8},
    {x = 132, y = 65, width = 31, height = 42, name = "drop_tree_b", type = "tree", style = "winter_forest", bitvalue = 8001, yoffset=21, xoffset=8},
    {x = 164, y = 1, width = 15, height = 16, name = "present_a", type = "present", style = "winter_forest", bitvalue = 2000, yoffset=0, xoffset=0},
    {x = 164, y = 19, width = 15, height = 16, name = "present_b", type = "present", style = "winter_forest", bitvalue = 2001, yoffset=0, xoffset=0},
    {x = 164, y = 36, width = 15, height = 16, name = "present_c", type = "present", style = "winter_forest", bitvalue = 2002, yoffset=0, xoffset=0},
    {x = 164, y = 55, width = 15, height = 16, name = "present_d", type = "present", style = "winter_forest", bitvalue = 2003, yoffset=0, xoffset=0},
    {x = 182, y = 1, width = 15, height = 18, name = "player", type = "player", style = "player", bitvalue = 9000, yoffset=2, xoffset=0},
    {x = 199, y = 1, width = 17, height = 7, name = "snow_a", type = "snow", style = "winter_forest", bitvalue = 3000, yoffset=0, xoffset=1},
    {x = 199, y = 9, width = 17, height = 10, name = "snow_b", type = "snow", style = "winter_forest", bitvalue = 3001, yoffset=0, xoffset=1},
    {x = 199, y = 21, width = 17, height = 14, name = "snow_c", type = "snow", style = "winter_forest", bitvalue = 3002, yoffset=0, xoffset=1},
    {x = 181, y = 37, width = 43, height = 18, name = "timer_box", type = "UI", style = "UI", bitvalue = 5000, yoffset=0, xoffset=0},
    {x = 181, y = 57, width = 43, height = 29, name = "present_box", type = "UI", style = "UI", bitvalue = 5001, yoffset=0, xoffset=0}
}

